// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkh7opo2f_Bo0BtKiJyzafVW0FWXTXuHk',
    appId: '1:683647933552:web:71373d308842e37f6de8b5',
    messagingSenderId: '683647933552',
    projectId: 'audio-meter',
    authDomain: 'audio-meter.firebaseapp.com',
    storageBucket: 'audio-meter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ZN-NAppMj0E7_spZC2N6cYh6y6cEwnM',
    appId: '1:683647933552:android:695a9c700e9c3f006de8b5',
    messagingSenderId: '683647933552',
    projectId: 'audio-meter',
    storageBucket: 'audio-meter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXzD87k6D0vkjfDvy0p-5l5-NERKC2VE',
    appId: '1:683647933552:ios:6b6002d9c13d43466de8b5',
    messagingSenderId: '683647933552',
    projectId: 'audio-meter',
    storageBucket: 'audio-meter.firebasestorage.app',
    iosBundleId: 'com.example.audiometer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjXzD87k6D0vkjfDvy0p-5l5-NERKC2VE',
    appId: '1:683647933552:ios:6b6002d9c13d43466de8b5',
    messagingSenderId: '683647933552',
    projectId: 'audio-meter',
    storageBucket: 'audio-meter.firebasestorage.app',
    iosBundleId: 'com.example.audiometer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkh7opo2f_Bo0BtKiJyzafVW0FWXTXuHk',
    appId: '1:683647933552:web:f56b16baff9598c86de8b5',
    messagingSenderId: '683647933552',
    projectId: 'audio-meter',
    authDomain: 'audio-meter.firebaseapp.com',
    storageBucket: 'audio-meter.firebasestorage.app',
  );
}
